services:
  pruebazurich:
    image: ${DOCKER_REGISTRY-}pruebazurich
    container_name: Zurich.Back
    build:
      context: .
      dockerfile: PruebaZurich/Dockerfile
    networks:
      - zurich-network
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Zurich.Db
    volumes: 
      - ./.containers/database:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123*
      - MSSQL_PID=Express
    networks:
      - zurich-network
  frontend:
    build:
      context: ./prueba-zurich
      dockerfile: Dockerfile
    container_name: Zurich.Front
    ports:
      - "4200:80"
    networks:
      - zurich-network
    depends_on:
      - pruebazurich
      
networks:
  zurich-network:
    driver: bridge