version: '3.8'

services:
  backend:
    build:
      context: ./PruebaZurich
    ports:
      - "5000:5000" 
    expose:
      - "5000"   
    depends_on:
      - db

  frontend:
    build:
      context: ./prueba-zurich
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123*
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: